# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "instagram"
client_id = "a185f2b72b360a900c149072accf83c1"
application_url = "https://artwork-tradition-bachelor-leeds.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://artwork-tradition-bachelor-leeds.trycloudflare.com/auth/shopify/callback",
  "https://artwork-tradition-bachelor-leeds.trycloudflare.com/authSa/shopify/callback",
  "https://artwork-tradition-bachelor-leeds.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ig-dungpv.myshopify.com"
